import { TeamMemberDbRow } from "./schema";

/**
 * 5 Canonical Verified Leadership profiles representing CodeXa's real organizational leadership
 * Strictly adheres to non-negotiable content rules: no invented achievements, client claims, or metrics.
 * Varun profile is imported from verified resume without exposing any private information (no phone, email, address, DOB).
 */
export const CANONICAL_INITIAL_PROFILES: Partial<TeamMemberDbRow>[] = [
  {
    id: "d63a0516-ab2f-4474-a3ca-8d549db5fbc2",
    slug: "ch-arshad",
    full_name: "CH. Arshad",
    display_name: "CH. Arshad",
    code_name: "SOUTH DEVELOPER",
    role_type: "Founder",
    primary_designation: "Founder & Technical Director",
    secondary_designation: "Full-Stack Architect & AI Systems",
    department: "Engineering, Architecture & Product Development",
    tagline: "Building resilient production systems and guiding CodeXa’s technical direction.",
    short_tagline: "Building resilient production systems and guiding CodeXa’s technical direction.",
    short_bio: "Founder and Technical Director of CodeXa Agency, responsible for technical architecture, engineering direction, production standards and secure product development.",
    full_bio: "CH. Arshad (SOUTH DEVELOPER) is the Founder and Technical Director of CodeXa Agency, responsible for overall technology architecture, engineering direction, production standards, and secure product development. He founded the CodeXa Developer Internship to build production-grade developers capable of shipping real-world software.",
    leadership_summary: "Leads CodeXa’s engineering and technology direction, including application architecture, frontend and backend systems, databases, AI-assisted products, developer tooling and production delivery reviews.",
    quote: "Build with purpose, architect for resilience, and always ship production-grade code.",
    responsibilities: [
      "Define the technical architecture for CodeXa products and client solutions",
      "Guide frontend, backend and database engineering decisions",
      "Review production readiness, performance and security",
      "Lead AI-system and developer-tooling exploration",
      "Establish engineering standards and delivery practices",
      "Support technical planning and implementation reviews",
    ],
    focus_areas: [
      "System Architecture",
      "Next.js and React",
      "AI Engineering",
      "Database Systems",
      "Developer Tooling",
      "Production Engineering",
    ],
    skills: ["Next.js", "React 19", "TypeScript", "System Architecture", "PostgreSQL", "AI Engineering", "Supabase", "CI/CD"],
    photo_url: "/assets/image-assests/founder.jpeg",
    image_path: "/assets/image-assests/founder.jpeg",
    image_bucket: "leadership",
    crop_x: 50,
    crop_y: 35,
    crop_scale: 1,
    image_crop_x: 50,
    image_crop_y: 35,
    image_zoom: 1,
    verification_status: "published",
    profile_completeness: 100,
    source_notes: "Verified canonical founder profile",
    is_public: true,
    status: "active",
    is_active: true,
    is_archived: false,
    sort_order: 1,
    is_featured: true,
  },
  {
    id: "a5e3eb9c-e7ed-4bd7-8e4a-e073c502b359",
    slug: "b-sanjay",
    full_name: "B. Sanjay",
    display_name: "B. Sanjay",
    code_name: "SPIDEYY !!",
    role_type: "Co-Founder",
    primary_designation: "Co-Founder & Platform Lead",
    secondary_designation: "Developer Platform & Distributed Workflows",
    department: "Platform Engineering & Developer Operations",
    tagline: "Connecting platform engineering, developer workflows and team execution.",
    short_tagline: "Connecting platform engineering, developer workflows and team execution.",
    short_bio: "Co-Founder and Platform Lead supporting candidate onboarding, developer workflows, team coordination and reliable platform delivery.",
    full_bio: "B. Sanjay (SPIDEYY !!) is the Co-Founder and Platform Lead at CodeXa Agency. He directs platform engineering operations, student onboarding pipelines, developer workflows, and team collaboration across projects.",
    leadership_summary: "Coordinates platform engineering and developer operations while helping the team move from requirements to structured implementation and delivery.",
    quote: "Great software is built by teams who care about every single line of code.",
    responsibilities: [
      "Coordinate platform engineering activities",
      "Organize developer workflows and technical handoffs",
      "Support candidate and intern onboarding",
      "Improve collaboration between design, frontend and backend contributors",
      "Assist with CI/CD and deployment workflows",
      "Track implementation progress and delivery readiness",
    ],
    focus_areas: [
      "Platform Engineering",
      "Developer Operations",
      "Team Coordination",
      "CI/CD",
      "TypeScript",
      "Candidate Onboarding",
    ],
    skills: ["Platform Engineering", "Developer Operations", "TypeScript", "CI/CD", "Next.js", "GitHub Actions", "Team Enablement"],
    photo_url: "/assets/image-assests/co-founder.jpeg",
    image_path: "/assets/image-assests/co-founder.jpeg",
    image_bucket: "leadership",
    crop_x: 50,
    crop_y: 28,
    crop_scale: 1,
    image_crop_x: 50,
    image_crop_y: 28,
    image_zoom: 1,
    verification_status: "published",
    profile_completeness: 100,
    source_notes: "Verified canonical co-founder profile",
    is_public: true,
    status: "active",
    is_active: true,
    is_archived: false,
    sort_order: 2,
    is_featured: true,
  },
  {
    id: "148ed82c-a0a1-40b1-b91f-9447726a0f9b",
    slug: "kishore",
    full_name: "Kishore",
    display_name: "Kishore",
    code_name: null,
    role_type: "CEO",
    primary_designation: "Chief Executive Officer",
    secondary_designation: "Strategic Partnerships & Business Operations",
    department: "Executive Strategy & Business Operations",
    tagline: "Turning strategy, partnerships and execution into sustainable growth.",
    short_tagline: "Turning strategy, partnerships and execution into sustainable growth.",
    short_bio: "Chief Executive Officer of CodeXa Agency, leading business strategy, partnerships, growth initiatives and operational alignment.",
    full_bio: "Kishore serves as Chief Executive Officer of CodeXa Agency, leading corporate strategy, business partnerships, executive execution, and organizational alignment to scale real-world developer learning and client solutions.",
    leadership_summary: "Guides company strategy and helps align product delivery, partnerships, recruitment and operational priorities with CodeXa’s long-term direction.",
    quote: "Execution turns ambitious vision into undeniable reality.",
    responsibilities: [
      "Guide business and operational strategy",
      "Develop partnerships and growth opportunities",
      "Coordinate leadership priorities",
      "Support product and service delivery planning",
      "Review organizational execution",
      "Help align recruitment and team capacity with projects",
    ],
    focus_areas: [
      "Strategic Leadership",
      "Business Operations",
      "Partnerships",
      "Product Delivery",
      "Growth",
      "Organizational Planning",
    ],
    skills: ["Strategic Leadership", "Business Operations", "Partnerships", "Product Delivery", "Growth Strategy", "Resource Planning"],
    photo_url: "/assets/image-assests/ceo.jpeg",
    image_path: "/assets/image-assests/ceo.jpeg",
    image_bucket: "leadership",
    crop_x: 50,
    crop_y: 25,
    crop_scale: 1,
    image_crop_x: 50,
    image_crop_y: 25,
    image_zoom: 1,
    verification_status: "published",
    profile_completeness: 100,
    source_notes: "Verified canonical CEO profile",
    is_public: true,
    status: "active",
    is_active: true,
    is_archived: false,
    sort_order: 3,
    is_featured: true,
  },
  {
    id: "c23e97f4-fc66-4efb-aede-04c42b542bdf",
    slug: "g-bhanu-prasad",
    full_name: "G. Bhanu Prasad",
    display_name: "G. Bhanu Prasad",
    code_name: "HAKAI",
    role_type: "CEO",
    primary_designation: "Chief Executive Officer",
    secondary_designation: "Technology Strategy & Talent Leadership",
    department: "Executive Technology & Talent Operations",
    tagline: "Aligning technology strategy, developer growth and recruitment execution.",
    short_tagline: "Aligning technology strategy, developer growth and recruitment execution.",
    short_bio: "CodeXa executive leading technology strategy, developer acceleration, recruitment pipelines and talent mentorship.",
    full_bio: "G. Bhanu Prasad (HAKAI) serves as Chief Executive Officer at CodeXa Agency, spearheading tech strategy, developer acceleration, high-standard candidate screening, and engineering capability programs.",
    leadership_summary: "Supports the connection between executive planning and technical team growth, with a focus on development practices, recruitment structure and mentorship.",
    quote: "Master the fundamentals, embrace modern tools, and always keep shipping.",
    responsibilities: [
      "Support technology and execution strategy",
      "Guide developer acceleration initiatives",
      "Coordinate recruitment pipelines",
      "Assist technical mentorship and team growth",
      "Support full-stack development direction",
      "Review talent readiness for project assignments",
    ],
    focus_areas: [
      "Executive Leadership",
      "Technology Strategy",
      "Recruitment Pipelines",
      "Full-Stack Development",
      "Talent Mentorship",
      "Developer Growth",
    ],
    skills: ["Technology Strategy", "Recruitment Architecture", "Full-Stack Development", "Talent Mentorship", "Developer Acceleration"],
    photo_url: "/assets/image-assests/4e56a053e3ee0019b13c19c5b3f614fe.jpg",
    image_path: "/assets/image-assests/4e56a053e3ee0019b13c19c5b3f614fe.jpg",
    image_bucket: "leadership",
    crop_x: 50,
    crop_y: 50,
    crop_scale: 1,
    image_crop_x: 50,
    image_crop_y: 50,
    image_zoom: 1,
    verification_status: "published",
    profile_completeness: 100,
    source_notes: "Verified canonical CEO profile",
    is_public: true,
    status: "active",
    is_active: true,
    is_archived: false,
    sort_order: 4,
    is_featured: true,
  },
  {
    id: "e7b92f15-8c34-4b52-9c1a-6d8e2f3a4b5c",
    slug: "p-varun",
    full_name: "Parlapalli Varun",
    display_name: "P. Varun",
    code_name: null,
    role_type: "COO",
    primary_designation: "Chief Operating Officer",
    secondary_designation: "Core Frontend & UI/UX Designer",
    department: "Product Design, Frontend & Operations",
    education_summary: "B.Tech in Cybersecurity, 2025–2029 Narasaraopeta Engineering College JNTU Kakinada",
    experience_summary: "Core frontend & UI/UX contribution at CodeXa Agency; NEC Portal frontend; ByteXL hackathon; CodeBegin/Vibe projects",
    tagline: "Designing clear product experiences and coordinating ideas into working interfaces.",
    short_tagline: "Designing clear product experiences and coordinating ideas into working interfaces.",
    short_bio: "B.Tech Cybersecurity student contributing to CodeXa Agency as a core frontend and UI/UX designer, with work focused on responsive interfaces, product experience and design-to-development execution.",
    full_bio: "Parlapalli Varun is a B.Tech Cybersecurity student at Narasaraopeta Engineering College (JNTU Kakinada) serving as Chief Operating Officer and Core Frontend & UI/UX Designer at CodeXa Agency. His focus spans intuitive interface architectures, responsive design systems, and converting functional specifications into polished digital experiences.",
    leadership_summary: "Supports CodeXa’s operational execution while contributing to frontend design, UI/UX structure, responsive experiences, product presentation and quality review.",
    quote: "Design with clarity, execute with discipline, and turn ideas into seamless user experiences.",
    responsibilities: [
      "Design responsive interfaces for web applications",
      "Convert product ideas and requirements into structured UI flows",
      "Support frontend implementation and visual consistency",
      "Coordinate design-to-development handoff",
      "Review mobile and desktop usability",
      "Assist product documentation and presentation",
      "Contribute cybersecurity-aware thinking to product design",
      "Support operational tracking and execution where assigned",
    ],
    focus_areas: [
      "UI/UX Design",
      "Frontend Development",
      "Responsive Web Design",
      "Product Design",
      "React and Next.js",
      "TypeScript",
      "Cybersecurity",
      "Design-to-Code",
    ],
    skills: ["UI/UX Design", "Figma", "React", "Next.js", "Tailwind CSS", "TypeScript", "Responsive Design", "Cybersecurity Basics"],
    linkedin_url: "https://linkedin.com/in/varun-parlapalli/",
    github_url: "https://github.com/varunparlapalli2008",
    photo_url: "/assets/image-assests/hero.jpeg",
    image_path: "/assets/image-assests/hero.jpeg",
    image_bucket: "leadership",
    crop_x: 50,
    crop_y: 50,
    crop_scale: 1,
    image_crop_x: 50,
    image_crop_y: 50,
    image_zoom: 1,
    verification_status: "published",
    profile_completeness: 100,
    source_notes: "Imported from verified candidate resume with private fields excluded",
    is_public: true,
    status: "active",
    is_active: true,
    is_archived: false,
    sort_order: 5,
    is_featured: true,
  },
];

export const INITIAL_VERIFIED_CONTRIBUTIONS = [
  {
    team_member_id: "e7b92f15-8c34-4b52-9c1a-6d8e2f3a4b5c",
    contribution_type: "design" as const,
    title: "CodeXa Apply Frontend & UI/UX",
    summary: "Core frontend layout, responsive component hierarchy, and design-to-code implementation.",
    project_name: "CodeXa Apply",
    project_url: "https://www.codeaxisapply.xyz",
    verification_status: "published" as const,
    is_public: true,
    display_order: 1,
  },
  {
    team_member_id: "e7b92f15-8c34-4b52-9c1a-6d8e2f3a4b5c",
    contribution_type: "engineering" as const,
    title: "NEC Student Portal UI",
    summary: "Designed responsive interfaces and student workflow navigation for campus portal.",
    project_name: "NEC Portal",
    verification_status: "published" as const,
    is_public: true,
    display_order: 2,
  },
  {
    team_member_id: "e7b92f15-8c34-4b52-9c1a-6d8e2f3a4b5c",
    contribution_type: "project" as const,
    title: "Passing of Digital Legacy",
    summary: "Frontend interface and architectural mockups built during CodeBegin / Vibe development sprint.",
    project_name: "Aegis Legacy",
    verification_status: "published" as const,
    is_public: true,
    display_order: 3,
  },
  {
    team_member_id: "e7b92f15-8c34-4b52-9c1a-6d8e2f3a4b5c",
    contribution_type: "engineering" as const,
    title: "ByteXL Python Chatbot",
    summary: "Conversational interface prototyping and natural language query response integration.",
    project_name: "ByteXL Chatbot",
    verification_status: "published" as const,
    is_public: true,
    display_order: 4,
  },
];

/**
 * Finds a matching canonical profile by UUID, slug, or normalized full/display name
 */
export function findMatchingCanonicalProfile(row: {
  id?: string;
  slug?: string;
  full_name?: string;
  display_name?: string;
  name?: string;
}): Partial<TeamMemberDbRow> | undefined {
  if (!row) return undefined;
  const nameToMatch = (row.full_name || row.display_name || row.name || "").toLowerCase().trim();

  return CANONICAL_INITIAL_PROFILES.find((c) => {
    if (row.id && c.id === row.id) return true;
    if (row.slug && c.slug === row.slug) return true;
    if (c.full_name && c.full_name.toLowerCase().trim() === nameToMatch) return true;
    if (c.display_name && c.display_name.toLowerCase().trim() === nameToMatch) return true;
    return false;
  });
}
