-- ==============================================================================
-- CODEXA APPLY V2 — SUPABASE POSTGRESQL PRODUCTION SCHEMA
-- Project: CodeXa Apply (Dedicated Project)
-- Region: Mumbai / ap-south-1
-- ==============================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. APPLICATIONS TABLE (Core Candidate Submissions)
create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  reference_id text not null unique,
  full_name text not null,
  date_of_birth text,
  gender text,
  email text not null,
  phone_number text not null,
  whatsapp_number text,
  city text,
  state text,
  country text default 'India',
  college_name text,
  degree text,
  branch text,
  graduation_year text,
  current_year_semester text,
  cgpa_percentage text,
  github_profile text,
  linkedin_profile text,
  portfolio_website text,
  other_profiles jsonb default '[]',
  primary_interest text,
  primary_role_applied text default 'Full-Stack Developer',
  experience_level text,
  total_score numeric(5, 2) default 0,
  score_band text default 'Review',
  genuineness_integrity_score numeric(5, 2) default 0,
  commitment_continuity_score numeric(5, 2) default 0,
  mindset_habits_score numeric(5, 2) default 0,
  technical_knowledge_score numeric(5, 2) default 0,
  learning_potential_score numeric(5, 2) default 0,
  interview_communication_score numeric(5, 2) default 0,
  commitment_signal text,
  skill_authenticity text,
  status text not null default 'Submitted',
  admin_notes jsonb default '[]',
  admin_tags jsonb default '[]',
  raw_submission jsonb default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_deleted boolean not null default false
);

create index if not exists applications_ref_idx on public.applications (reference_id);
create index if not exists applications_email_idx on public.applications (email);
create index if not exists applications_status_idx on public.applications (status);

-- 2. APPLICATION STATUS HISTORY TABLE
create table if not exists public.application_status_history (
  id uuid primary key default gen_random_uuid(),
  application_id uuid references public.applications(id) on delete cascade,
  reference_id text not null,
  previous_status text,
  new_status text not null,
  note text,
  changed_by text not null default 'System',
  created_at timestamptz not null default now()
);

-- 3. ADMIN SESSIONS TABLE (Zero-plain-token storage)
create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  device_label text,
  user_agent text,
  ip_hash text,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

-- 4. ADMIN LOGIN ATTEMPTS (Rate limiting)
create table if not exists public.admin_login_attempts (
  id bigint generated by default as identity primary key,
  identifier_hash text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists admin_login_attempts_idx on public.admin_login_attempts (identifier_hash, created_at);

-- 5. ADMIN AUDIT LOGS TABLE
create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  details text not null,
  admin_identifier text default 'Master Admin',
  created_at timestamptz not null default now()
);

-- 6. EMAIL LOGS TABLE
create table if not exists public.email_logs (
  id uuid primary key default gen_random_uuid(),
  application_id uuid references public.applications(id) on delete set null,
  email_type text not null,
  recipient text not null,
  provider_message_id text,
  status text not null,
  error_message text,
  created_at timestamptz not null default now()
);

-- 7. TEAM PROFILES TABLE (Leadership CMS)
create table if not exists public.team_profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  designation text not null,
  role_type text not null default 'Core',
  bio text,
  quote text,
  photo_url text,
  email text,
  phone text,
  whatsapp text,
  roles jsonb default '[]',
  skills jsonb default '[]',
  display_order integer default 0,
  is_featured boolean default true,
  is_visible boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Seed Initial Leadership Profiles
insert into public.team_profiles (name, designation, role_type, bio, quote, photo_url, email, whatsapp, roles, skills, display_order)
values
(
  'Ashu',
  'Founder & Technical Director',
  'Founder',
  'Founder of CodeXa Agency. Focuses on AI agent architecture, developer tools, hosting platforms, Discord automation, 3D animated web experiences, secure application portals, and recruitment systems.',
  'I don''t just write code, I build solutions that create impact.',
  '/assets/image-assests/128acbeb739b3eb8bc4d1d9ae15fcfb2.jpg',
  'ashuchinthapalli3900@gmail.com',
  '+91 88979 01413',
  '["Founder", "Technical Direction", "AI Architecture", "Product Strategy"]',
  '["EDITH AI", "CODEXA IDE", "Claude Code API", "Ethical Hacking", "3D Web", "Full-Stack"]',
  1
),
(
  'Deepak',
  'Co-Founder & Operations Lead',
  'Co-Founder',
  'Co-Founder of CodeXa Agency. Supports the agency through team coordination, community engagement, application guidance, internship communication, and student query resolution.',
  'Connecting people, supporting progress, and keeping the journey smooth.',
  '/assets/image-assests/2299fdd2a1d01339a71af61a2c7e9cac.jpg',
  'contact@codxa-agency.online',
  '+91 94942 45412',
  '["Co-Founder", "Agency Operations", "Team Coordination", "Internship Coordination", "Program Support"]',
  '["Team Coordination", "Operations Management", "Student Support", "Community Building"]',
  2
),
(
  'Kishore',
  'Chief Executive Officer (CEO)',
  'CEO',
  'CEO of CodeXa Agency. Drives business strategy, agency partnerships, growth initiatives, project coordination, and administration. Oversees operational scaling.',
  'Scaling execution, driving innovation, and accelerating developer careers.',
  '/assets/image-assests/ed14ea822462d93c926056fcfd9db4c5 (1).jpg',
  'business@codxa-agency.online',
  '+91 70758 00951',
  '["CEO", "Business Strategy", "Growth & Partnerships", "Project Coordination", "Administration"]',
  '["Business Strategy", "Growth Marketing", "Project Management", "Organizational Leadership"]',
  3
)
on conflict do nothing;

-- 8. SITE SETTINGS & ASSETS METADATA
create table if not exists public.site_assets (
  id uuid primary key default gen_random_uuid(),
  asset_key text not null unique,
  name text not null,
  asset_url text not null,
  asset_type text not null,
  section text not null,
  alt_text text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Strict server-only access; all applicant operations execute through Next.js server.
-- ==============================================================================
alter table public.applications enable row level security;
alter table public.application_status_history enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.admin_login_attempts enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.email_logs enable row level security;
alter table public.team_profiles enable row level security;
alter table public.site_assets enable row level security;

-- Public read-only for public team profiles & site assets if needed by frontend
create policy "Public can view visible team profiles"
  on public.team_profiles for select
  using (is_visible = true);

create policy "Public can view active site assets"
  on public.site_assets for select
  using (is_active = true);
